version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
